### ISSUE TITLE
Ensure Discord #faq channel content exists on wiki

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver.Web#67]
- [x] Disable osu!'s "map raw input to osu! window"
- [x] OTD udev rules
- [x] Error 1: Windows tablet not detected
- [x] Error 2: Windows Gaomon/Huion not detected
- [x] Error 3: Linux ArgumentOutOfRangeException
- [x] Error 4: Failed to initialize virtual tablet/pointer
- [x] Error 5: Connecting to daemon
- [x] Valorant Guide
- [x] Windows pressure support
- [x] Installer deprecation (or leave it in)

Once everything is marked off we can leave the titles and replace the text with links.

Should leave Tablet Support status as-is

**Comment by jamesbt365** [comment]
- Disable osu!'s "map raw input to osu! window" is done already [here](http://opentabletdriver.net/Wiki/FAQ/Windows#map-raw-input) (should be moved to a general location instead of just the windows FAQ as this does happen with lazer and on wine on stable but i'll do more testing on that before moving it)
- OTD udev rules [here](http://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams) (maybe should also include or reword it so it also says about the hiddraw error i always see in diagnostics?)
- Error 1: Windows tablet not detected. I don't think i've seen this in diagnostic data, is this needed anymore? (not on the site)
- Error 2: Windows Gaomon/Huion not detected [here](http://opentabletdriver.net/Wiki/FAQ/Windows#uclogic-supported-undetected)
- Error 3: Linux ArgumentOutOfRangeException [here](http://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams), [here](http://opentabletdriver.net/Wiki/FAQ/Linux#ghost-cursor) and [here](http://opentabletdriver.net/Wiki/FAQ/Linux#argumentoutofrangeexception)
- Error 4: Failed to initialize virtual tablet/pointer. [here](http://opentabletdriver.net/Wiki/FAQ/Linux#fail-virtual-device)
- Error 5: Connecting to daemon (this should maybe be added but its mentioned in the install guide?)
- Valorant Guide, not yet.
- Windows pressure support, only mention of this is in the plugin manager which shows the plugin.
- Installer deprecation. The installer is not mentioned at all on the website anymore, nobody should be finding it and the cases including it have dropped immensely now, worth adding something anyway?

**Comment by gonX** [comment]
Yep, looks fine - the raw input stuff has correct workaround but wrong explanation, but that's tracked in #58
